### ISSUE TITLE
Something's fishy about the AmphibiaWeb resource

### ISSUE THREAD

**Issue by KatjaSchulz** [EOL/eol_php_code#152]
@eliagbayani   AmphibiaWeb is a connector, right?  Something went wrong with this resource.  It looks like a lot of the species articles are now associated with genus names, so we have multiple genera listed in their hierarchy.  For example, check out this page: http://eol.org/pages/45883912/overview

There are 7 different versions of the Fejervarya page, each with content for a different Fejervarya species.  Could you please check if the problem is on their end or ours?  Thanks!

**Comment by eliagbayani** [comment]
Sure, will check this one today @KatjaSchulz .

**Comment by eliagbayani** [comment]
I saw the problem. The XML structure of their [XML dump](http://amphibiaweb.org/amphib_dump.xml) has changed.

They’re now using genus+specificepithet instead of genus+species in the past.
I’ve now updated the connector, committed it, sent pull-request.

I’ve also now uploaded latest EOL DWC-A resource to our server so we can re-harvest this anytime to fix the problem the soonest.
Resource now ready for the harvest [queue](https://github.com/EOL/tramea/issues/186).

Statistics
    http://eol.org/schema/reference/reference:4920
    http://eol.org/schema/agent/agent:578
    http://purl.org/dc/dcmitype/Text: 7694
    http://rs.tdwg.org/dwc/terms/taxon:2172
    http://rs.gbif.org/terms/1.0/vernacularname:1955

**Comment by KatjaSchulz** [comment]
Thanks Eli!

**Comment by KatjaSchulz** [comment]
Apparently, AmphibiaWeb has been reharvested, but this problem persists.  We still have multiples of genera in this hierarchy: http://eol.org/pages/45884370/names 

Possibly the wrong version of the resource was harvested?

**Comment by eliagbayani** [comment]
Hi @JRice , may I request loading of my pull-request here:
https://github.com/EOL/eol_php_code/pull/154

Code here will fix the problem on AmphibiaWeb. Thanks.

**Comment by eliagbayani** [comment]
Hi @KatjaSchulz , I've uploaded the correct dwc-a resource [before](https://github.com/EOL/eol_php_code/issues/152#issuecomment-239060613) but that seems not enough. The old connector overwrote it. I will just run the connector from server once latest connector is loaded. Will keep an eye on this one. Thanks.

**Comment by eliagbayani** [comment]
Thanks @JRice, I saw the changes now reflected.

**Comment by eliagbayani** [comment]
I ran the connector from the server and correct dwc-a resource now generated.

Hi @jhammock, may we request another [queuing](https://github.com/EOL/tramea/issues/186) of this resource:
http://eol.org/content_partners/7/resources/21
We should be able to get the right resource this time. Thanks.

**Comment by KatjaSchulz** [comment]
Everything looks great now.  Species have their own pages. Thanks!

**Comment by eliagbayani** [comment]
@KatjaSchulz @jhammock 
Glad to hear that. Thanks everybody.
